### ISSUE TITLE
awscdk-v1-stack-finder does not return some V1 stacks

### ISSUE THREAD

**Issue by susmm1** [cdklabs/awscdk-v1-stack-finder#345]
We are currently in the process of upgrading our V1 stack to V2. Have been using awscdk-v1-stack-finde to get an inventory of all stacks that need to be upgraded. Found that awscdk-v1-stack-finder does not return all stacks that are yet to be upgraded. It does return some v1 stacks but there are at least 2 stacks missing from the output.

**Comment by peterwoodworth** [comment]
Can you please provide the Analytics value on the CDKMetadata resource for the v1 stacks this is not locating?

**Comment by susmm1** [comment]
@peterwoodworth, i am fairly new to aws cdk, how or where do I find the Analytics value on the CDKMetadata resource?

**Comment by peterwoodworth** [comment]
Check the deployed CloudFormation templates of the stacks that are affected. It should be towards the bottom of the CloudFormation template

**Comment by susmm1** [comment]
@peterwoodworth, here are all the stacks from a single amazon pipeline that are not showing up in the output. 

"Analytics": "v2:deflate64:H4sIAAAAAAAA/zWMyw6CMBBFv4V9HSiYuPUV1wY/wIztGKvtlPQhUcK/CxpX995zk9NABVJWxRrdm8vOdGQNU4Q9dda/HHE6JVQPIUGuaqgK59kr/YBhd+UjBnSUKIhp7Dxrk4xn0VL0OSgS2MfzYNFdNMIhs5rfLUYSyvqse0zqBsPGYnCz4FvGUUyimEJWaYZ/1yjYa4J7LJ9yCbWEprhHYxYhczKOoP3lB2nZwtTOAAAA"
"Analytics": "v2:deflate64:H4sIAAAAAAAA/zVOy07DMBD8ltzNNk6RuCIVIY5R6B0Zewvb2uvIj6Jg5d+x03Ka2dmZnd1DD0XKvntW7pd3M81oiTHCC87WLw45vSelL0L2w93zvZigoLw1OGJMU+YJo89BYxSHE2+LEUOkmGr84PlEXzmoRJ7XVUiQTwP0nfPstblAqZFRBeUwYWj5GjDUzEL9xI9ilfs0te81s97UavnnqyDloEzeYpM3HL0lvbTxxmplvRhTyDptpvuvq2BvEM5xd5WPMEjYd+dI9BAyJ3II0w3/AAJgKOQhAQAA"
"Analytics": "v2:deflate64:H4sIAAAAAAAA/1WQzW7CMBCEn4X7diGkUq8tIKpWrYTCoUe0OAs18U/ktUE0yrvXCVw4jXc1/saeEmdYFLPJK9k/N211y0Y7Flxxa/zVsovbSKqBAouXOc4m1juv6ga75cFtKJDlyAHysPSu1lF7B3SRXSclLpJqOC5IGDRZ7CpveHCOuvFGq+sw3k49HE3iEbsMdDE36Kff92DI7mvCdXJq4I9Aidwe7gvZRZJGsPsajR/u7BuG94zLTw8xM6rkepByRyIcBd8GeURg90M6Qr4Q+ZvUb+5gyH+Yt0kp5ho2GQNr0gaGAoxh0wOfc1OZUqX7H7P2PVQsPgWVVzkjhqQijOGZe9TuODrvlh6crxlPMj0XzzgvsJycROunkFzUlrG66T9kG8FbsAEAAA=="
"Analytics": "v2:deflate64:H4sIAAAAAAAA/1VQy07DMBD8lt7NtmmQuEKLikAghfTAsTLOtrjxI3jtViXKv7NOi0RPs2OPZ7xTwgyKYja5l/bHTTvdodEOCR6xM/5k0cV1lKoVBRR3c5hNrHdeNS30y62rZJAWIwbBZOldo6P2TsgjbXoqYZFUi3EhCYWWFvraG8zKEStvtDplep4GsTMJR9tlkEdzNn3xn4Mw0n42EvpVcioHjI5/JKv+zxUGq4mYDYIidtvLHW2ipJagfx3dnt3BtyieOJP3C5GD6pSflBtJhJHgIcO1BfQfUkfBDyK+SfXFReXIK75OSiE2omIbsZLaiNySMWjY/JvgPWHCcQM8cLnsWadLLYzDIGokn4LiI06MIakoxq9wyk673ai8SAbhfIOwp+mhuIV5AeVkT1rfhOSitgj1GX8BY894beMBAAA="
"Analytics": "v2:deflate64:H4sIAAAAAAAA/2VRTU8CMRD9LdzHgQUTrwqK0WiCcPBISnfAst127bQQ3Ox/t93lI+ilM6/z8WbejHCAWTbo3Yvyx/QrVZFWhhgfqdL2UJLxCy9kARlmd0Mc9EprrMwLrCdrMxNOlOTJQQQTa3LllTUg9rys+Zux/ggUKAU7p31nVit5OH92sAEeYT0OsiCfQkevM5eKK9yBsWBK1UvBTJ7xIRlQosR6bnVL3tpLkxPjRgdq13i1q3YBJ/aaXANalKtcYD0NRqaFEgWcQMo8+0+7pI8NTtK7qCplNin8/zcO6KlaH8t46QUXUZ7nOEFU1/k4wTwYeGuJX8zOFvSnBOtPoTzEbB+byq94o0R1hRdBSqIcZlEKmAqlIR1Ia9KxGUdBFt7FYa6udgZNA3PidmiIp2TvgvTQqhlJNsfVTikNGJsTbrm/y25xmOGot2WlblwwXpWE887+ArnBKCddAgAA"
"Analytics": "v2:deflate64:H4sIAAAAAAAA/1VPy07DMBD8ltzNNm4qcYUWCQmpUhUOHCPjbIObeB1516AS5d9xUg5wmh3NQ7MVlKB1WTwY/02b0Y04OEKGJxyHcPVI8irG9kqDvt9CWfhAwbY9TIcznUw0HgWjyuQQqHXiAinzxc3EFeyT7VH2hlFx1RhmFIbHBZQzHqY6DLgkVzyFwdnrQm/XrLohIWT+Et4VC47nRHbp50YM9wzPWc/bomRDnei/B6Y340RlXfBo7Ef+aen+y+dZ1cghRZulHJGYrKh1X7Z1jrp13K9lVhRahAtvPvUOthqq4sLO3cVE4jxCfcMfAV/oU08BAAA="
"Analytics": "v2:deflate64:H4sIAAAAAAAA/02NzU4DMQyEn2Xvwd20SL0CRb0hofIAlUkMuE3sVeJQtat9d7r8SJxmPo30zQp68L7v7jBfZDHwQImFKjzSkPScSezFMBydB79eQt9lFQ3xCOPmTZ6xYCaj4q6wUYlsrOJ2VLWVQA5PdT8mzK8RYdskzOsDVnIhaYsntPAB433CkmfBd5lc0vcK4xNZ4bDl9Gv/z9PkrmfVSgs2b39/kxONBIe6+PS3sPSw6g6V+aY0Mc4Eu5/8AknRgNTyAAAA"
"Analytics": "v2:deflate64:H4sIAAAAAAAA/1WQT2/CMAzFPwt3z1A6adcNJqZNm8TKYUdkUsNC86erExCr+t2XBi47vdh6+T3bJc6wKGaTR7K/btrqlo12LPjMrfEXyy5sAqkGCiwe5jibWO+8qhvsl3u3po4sB+4gFUvvah20d0Bn2fZS4iKqhsOChEGTxb7yhkdn1rU3Wl3G8voa4GAiZ+yyo7O5Qt/8bgBDdlcTrqJTIz8DJXC7vzVkG0gawf49G1/dyTcMLwmXRu9CYlTRDSDllkQ4CD6N8h+B/RfpAOlD4A9S3+kGY/6/ehOVYq5hnTCwIm1gPIAxbBL8R/AzcuQ8HZ/S3RKzireNkw4DVCw+diq1UmLoogqQR0kpB+0O2XmzDOB8zXiU6am4x3mB5eQoWt910QVtGaur/gGY9PXgvgEAAA=="
"Analytics": "v2:deflate64:H4sIAAAAAAAA/zWMzQrCMBCEn6X3uG1awatQ8Sz1ASQmK6RNNiU/ioa+u2nF08zwzUwHDXDeVEdhP1TPekajCQOccDbubZHiNQo5MQ780EJTWUdOqgly/6CL8MJiRM9K6B0pHbUjJl7hlrWwkAdncGWrLswIe1cC8jmR3IqF/P2ysHIQok8ybgsMLnlZVuQUwhjqJ99Dy6GrxqD1zieK2iIMP/0Ca2PO+8YAAAA="
"Analytics": "v2:deflate64:H4sIAAAAAAAA/0WM3QqCQBCFn8X7bXQ16DaqBxB7gFjWCUbdGdmfwsR3zzLo6js/nFNBAVoX2dG4F+cjjTgQY4ALjoNMDjleo7G90qAPJRSZExbb9jCf71wbbxxG9Go1Z+GWIgkr8wy3UMF8SrbH+Ol+akMtA9npH29+UetBiD7Z76LBIMlbXBRLi9CF/KH3UGqosi4Q7XziSA6h2fgGUa/TIMYAAAA="
